# frozen_string_literal: true

Prawn::Fonts::AFM.hide_m17n_warning = true

module Payroll
  class PayslipPdfExporter
    def initialize(payroll_item:)
      @item = payroll_item
      @run = payroll_item.payroll_run
      @employee = payroll_item.employee
      @company = @run.company
    end

    def call
      Prawn::Document.new(page_size: "A4") do |pdf|
        pdf.text ascii(@company.name), size: 16, style: :bold
        pdf.text "Payslip", size: 14, style: :bold
        pdf.move_down 8
        pdf.text "Period: #{@run.period_start} - #{@run.period_end}", size: 10
        pdf.text "Generated: #{(@run.generated_at || @item.updated_at).strftime('%Y-%m-%d %H:%M')}", size: 9, color: "666666"
        pdf.move_down 16

        pdf.text "Employee", size: 11, style: :bold
        pdf.text ascii(@employee.full_name)
        pdf.text "#{@employee.employee_number} - #{@employee.email}"
        pdf.text ascii(@employee.job_title) if @employee.job_title.present?
        pdf.move_down 16

        currency = @item.currency.presence || @company.currency
        rows = [
          [ "Component", "Amount (#{currency})" ],
          [ "Salary", money(@item.salary_cents) ],
          [ "Bonus", money(@item.bonus_cents) ],
          [ "Commission", money(@item.commission_cents) ],
          [ "Tax", "-#{money(@item.tax_cents)}" ],
          [ "Insurance", "-#{money(@item.insurance_cents)}" ],
          [ "Net pay", money(@item.net_cents) ]
        ]

        pdf.table(rows, header: true, width: pdf.bounds.width, cell_style: { size: 10 }) do
          row(0).font_style = :bold
          row(-1).font_style = :bold
        end

        pdf.move_down 24
        pdf.text "This document is generated by EMS for employee records.", size: 8, color: "888888"
      end.render
    end

    private

    def money(cents)
      format("%.2f", cents.to_i / 100.0)
    end

    def ascii(value)
      value.to_s.encode("Windows-1252", invalid: :replace, undef: :replace, replace: "?")
    end
  end
end
